# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.realtime.grpc_gen import robot_pb2 as app_dot_realtime_dot_grpc__gen_dot_robot__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/realtime/grpc_gen/robot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotStreamStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamJoints = channel.unary_stream(
                '/vla.robot.v1.RobotStream/StreamJoints',
                request_serializer=app_dot_realtime_dot_grpc__gen_dot_robot__pb2.StreamRequest.SerializeToString,
                response_deserializer=app_dot_realtime_dot_grpc__gen_dot_robot__pb2.JointFrame.FromString,
                _registered_method=True)
        self.StreamRates = channel.unary_stream(
                '/vla.robot.v1.RobotStream/StreamRates',
                request_serializer=app_dot_realtime_dot_grpc__gen_dot_robot__pb2.RatesRequest.SerializeToString,
                response_deserializer=app_dot_realtime_dot_grpc__gen_dot_robot__pb2.Rates.FromString,
                _registered_method=True)


class RobotStreamServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamJoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRates(self, request, context):
        """~2 Hz, measured over the last 2 s
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamJoints': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamJoints,
                    request_deserializer=app_dot_realtime_dot_grpc__gen_dot_robot__pb2.StreamRequest.FromString,
                    response_serializer=app_dot_realtime_dot_grpc__gen_dot_robot__pb2.JointFrame.SerializeToString,
            ),
            'StreamRates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRates,
                    request_deserializer=app_dot_realtime_dot_grpc__gen_dot_robot__pb2.RatesRequest.FromString,
                    response_serializer=app_dot_realtime_dot_grpc__gen_dot_robot__pb2.Rates.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vla.robot.v1.RobotStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vla.robot.v1.RobotStream', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotStream:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamJoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vla.robot.v1.RobotStream/StreamJoints',
            app_dot_realtime_dot_grpc__gen_dot_robot__pb2.StreamRequest.SerializeToString,
            app_dot_realtime_dot_grpc__gen_dot_robot__pb2.JointFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vla.robot.v1.RobotStream/StreamRates',
            app_dot_realtime_dot_grpc__gen_dot_robot__pb2.RatesRequest.SerializeToString,
            app_dot_realtime_dot_grpc__gen_dot_robot__pb2.Rates.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
