"""Compose a robot arm and an end effector into one robot USD under the sim folder.

    uv run --no-project --with usd-core python scripts/compose-sim-robot.py \
        ufactory_xarm7 inspire_rh56bfx ufactory_xarm7_inspire_rh56bfx

writes robots/<output-id>/<output-id>.usda (sim folder: VLA_SIM_DIR, default data/sims): a small
layer whose default prim references the arm (robots/<arm-id>) and, as its child "tool", the tool
(tools/<tool-id>), both by relative paths. The tool's base body sits on the arm's flange frame
(--flange, default link_eef) at the arm's zero joint configuration, rolled by --roll degrees about
the flange Z, and a FixedJoint "tool_joint" ties it to the flange's rigid body (its parent link).
The tool stops being an articulation of its own: its ArticulationRootAPI is deleted and its world
joints and PhysicsScene are deactivated, so sim/runner/scene.py pins the arm's base. The arm's
joints start at their drive targets (its rest pose; --zero keeps the authored start), since at the
zero configuration a long tool can reach into the floor or table. Re-run it after changing either
asset. pxr (usd-core) only.
"""

import argparse
import math
import os
from pathlib import Path

from pxr import Gf, Sdf, Usd, UsdGeom, UsdPhysics

REPO_ROOT = Path(__file__).resolve().parent.parent
USD_EXTS = (".usd", ".usda", ".usdc")


def sim_dir() -> Path:
    p = Path(os.environ.get("VLA_SIM_DIR") or Path(os.environ.get("VLA_DATA_DIR", "data")) / "sims")
    return p if p.is_absolute() else REPO_ROOT / p


def usd_file(folder: Path, name: str) -> Path:
    for ext in USD_EXTS:
        for p in (folder / name / f"{name}{ext}", folder / f"{name}{ext}"):
            if p.is_file():
                return p
    raise SystemExit(f"no USD for '{name}' in {folder}")


def find(root: Usd.Prim, name: str) -> Usd.Prim:
    for p in Usd.PrimRange(root):
        if p.GetName() == name:
            return p
    raise SystemExit(f"no prim named '{name}' under {root.GetPath()}")


def rigid_parent(prim: Usd.Prim) -> Usd.Prim:
    p = prim
    while p and not p.HasAPI(UsdPhysics.RigidBodyAPI):
        p = p.GetParent()
    if not p:
        raise SystemExit(f"{prim.GetPath()} is not under a rigid body")
    return p


def tool_base(tool: Usd.Prim) -> Usd.Prim:
    """The tool's base body: its articulation root when that is a body, else its first body."""
    bodies = [p for p in Usd.PrimRange(tool) if p.HasAPI(UsdPhysics.RigidBodyAPI)]
    roots = [p for p in bodies if p.HasAPI(UsdPhysics.ArticulationRootAPI)]
    if not bodies:
        raise SystemExit(f"tool {tool.GetPath()} has no rigid body")
    return (roots or bodies)[0]


def pose(m: Gf.Matrix4d) -> tuple[Gf.Vec3f, Gf.Quatf]:
    m = Gf.Matrix4d(m).RemoveScaleShear()
    return Gf.Vec3f(m.ExtractTranslation()), Gf.Quatf(m.ExtractRotationQuat())


def start_at_rest(root: Usd.Prim) -> None:
    """Initial joint state = drive target for every arm joint that has both."""
    for p in Usd.PrimRange(root):
        if not p.IsA(UsdPhysics.Joint):
            continue
        for kind in ("angular", "linear"):
            target = p.GetAttribute(f"drive:{kind}:physics:targetPosition")
            state = p.GetAttribute(f"state:{kind}:physics:position")
            if target and state and target.Get() is not None:
                state.Set(target.Get())


def compose(arm_id: str, tool_id: str, out_id: str, flange: str, roll: float, rest: bool) -> Path:
    sims = sim_dir()
    arm_file = usd_file(sims / "robots", arm_id)
    tool_file = usd_file(sims / "tools", tool_id)
    out = sims / "robots" / out_id / f"{out_id}.usda"
    out.parent.mkdir(parents=True, exist_ok=True)
    if out.exists():
        out.unlink()

    stage = Usd.Stage.CreateNew(str(out))
    UsdGeom.SetStageUpAxis(stage, UsdGeom.Tokens.z)
    UsdGeom.SetStageMetersPerUnit(stage, 1.0)
    root = stage.DefinePrim(f"/{out_id}", "Xform")
    stage.SetDefaultPrim(root)
    root.GetReferences().AddReference(os.path.relpath(arm_file, out.parent))
    stage.GetRootLayer().documentation = (
        f"{arm_id} with {tool_id} on {flange}; generated by scripts/compose-sim-robot.py"
    )

    if rest:
        start_at_rest(root)

    cache = UsdGeom.XformCache()
    flange_prim = find(root, flange)
    link = rigid_parent(flange_prim)
    flange_world = cache.GetLocalToWorldTransform(flange_prim)
    root_world = cache.GetLocalToWorldTransform(root)
    link_world = cache.GetLocalToWorldTransform(link)
    # Tool base frame = the flange frame rolled about its Z (row-vector matrices: local * parent)
    rolled = Gf.Matrix4d().SetRotate(Gf.Rotation(Gf.Vec3d(0, 0, 1), roll)) * flange_world

    tool = stage.DefinePrim(root.GetPath().AppendChild("tool"), "Xform")
    tool.GetReferences().AddReference(os.path.relpath(tool_file, out.parent))
    base = tool_base(tool)
    base_in_tool = (
        cache.GetLocalToWorldTransform(base) * cache.GetLocalToWorldTransform(tool).GetInverse()
    )
    # Tool prim transform (relative to the root) that puts its base body on the rolled flange
    tool_local = base_in_tool.GetInverse() * rolled * root_world.GetInverse()
    pos, rot = pose(tool_local)
    xf = UsdGeom.Xformable(tool)
    xf.ClearXformOpOrder()
    xf.AddTranslateOp().Set(Gf.Vec3d(pos))
    xf.AddOrientOp().Set(rot)

    # One articulation: the arm's. The tool's own root, world joints and scene go
    for p in Usd.PrimRange(tool):
        if p.HasAPI(UsdPhysics.ArticulationRootAPI):
            p.RemoveAPI(UsdPhysics.ArticulationRootAPI)
        if p.IsA(UsdPhysics.Scene):
            p.SetActive(False)
        elif p.IsA(UsdPhysics.Joint):
            j = UsdPhysics.Joint(p)
            if not j.GetBody0Rel().GetTargets() or not j.GetBody1Rel().GetTargets():
                p.SetActive(False)

    cache.Clear()
    pos0, rot0 = pose(rolled * link_world.GetInverse())
    joint = UsdPhysics.FixedJoint.Define(stage, root.GetPath().AppendChild("tool_joint"))
    joint.CreateBody0Rel().SetTargets([link.GetPath()])
    joint.CreateBody1Rel().SetTargets([base.GetPath()])
    joint.CreateLocalPos0Attr(pos0)
    joint.CreateLocalRot0Attr(rot0)
    joint.CreateLocalPos1Attr(Gf.Vec3f(0, 0, 0))
    joint.CreateLocalRot1Attr(Gf.Quatf(1, 0, 0, 0))

    stage.GetRootLayer().Save()
    gap = (
        cache.GetLocalToWorldTransform(base).ExtractTranslation() - rolled.ExtractTranslation()
    ).GetLength()
    print(f"wrote {out} (tool base {base.GetPath()} on {link.GetPath()}, offset {gap:.2e} m)")
    if not math.isfinite(gap) or gap > 1e-4:
        raise SystemExit("the tool base is not on the flange")
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("arm", help="robot id under robots/, e.g. ufactory_xarm7")
    ap.add_argument("tool", help="tool id under tools/, e.g. inspire_rh56bfx")
    ap.add_argument("out", help="output robot id, e.g. ufactory_xarm7_inspire_rh56bfx")
    ap.add_argument("--flange", default="link_eef", help="arm prim the tool base sits on")
    ap.add_argument("--roll", type=float, default=0.0, help="tool roll about the flange Z (deg)")
    ap.add_argument("--zero", action="store_true", help="keep the arm's authored start pose")
    a = ap.parse_args()
    compose(a.arm, a.tool, a.out, a.flange, a.roll, not a.zero)


if __name__ == "__main__":
    main()
